import baseTheme from '@rebass/preset';
import colors from './colors.json';

export const theme = {
  ...baseTheme,
  colors,
  queries: {
    xs: '@media screen and (max-width: 40em)',
    sm: '@media screen and (min-width: 40em) and (max-width: 52em)',
    md: '@media screen and (min-width: 52em) and (max-width: 64em)',
    lg: '@media screen and (min-width: 64em)',
  },
  buttons: {
    empty: {
      p: 0,
      border: 0,
      m: 0,
      background: 'transparent',
    },
    secondary: {
      boxSizing: 'border-box',
      textAlign: 'center',
      textDecoration: 'none',
      padding: '8px 16px',
      border: '0px none',
      color: colors.muted,
      background: colors.secondary,
      borderRadius: '4px',
      fontWeight: '600',
      fontSize: '20px',
    },
    muted: {
      boxSizing: 'border-box',
      textAlign: 'center',
      textDecoration: 'none',
      padding: '8px 16px',
      border: '0px none',
      color: colors.secondary,
      background: colors.muted,
      borderRadius: '4px',
      fontWeight: '600',
      fontSize: '20px',
    },
    background: {
      boxSizing: 'border-box',
      textAlign: 'center',
      textDecoration: 'none',
      padding: '8px 16px',
      border: '0px none',
      color: colors.secondary,
      background: colors.background,
      borderRadius: '4px',
      fontWeight: '600',
      fontSize: '20px',
    },
    outline: {
      boxSizing: 'border-box',
      textAlign: 'center',
      textDecoration: 'none',
      padding: '8px 16px',
      border: '0px none',
      color: colors.secondary,
      background: 'transparent',
      borderRadius: '4px',
      fontWeight: '600',
      fontSize: '20px',
      boxShadow: '0px 0px 0px 2px inset',
    },
  },
  fonts: {
    body: 'Cabin, Open Sans, sans-serif',
    heading: 'inherit',
    monospace: 'monospace',
  },
};
