name: 'Build Setup'
description: 'Setup node and install dependencies'

runs:
  using: 'composite'
  steps:
    - name: Setup bun 🔧
      uses: oven-sh/setup-bun@v1
    - name: Install dependencies
      shell: bash
      run: bun install
