name: Update

on:
  schedule:
    - cron: 0 0 * * 3

  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/actions-package-update.yml'

jobs:
  gatsby-package-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: set remote url
        run: git remote set-url --push origin https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY

      - name: package-update
        uses: taichi/actions-package-update@master
        env:
          AUTHOR_EMAIL: '62586190+process-analytics-bot@users.noreply.github.com'
          AUTHOR_NAME: 'process-analytics-bot'
          EXECUTE: "true"
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}
          COMMIT_MESSAGE: "chore(deps-dev)"
          LOG_LEVEL: debug
        with:
          args: -u --verbose --dep dev --color --peer -f "/^gatsby.*$/"