name: Build PR

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/build-pr.yml'
      - 'src/**/*'
      - 'gatsby-browser.tsx'
      - 'gatsby-config.ts'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'
      - '.nvmrc'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Build Setup
        uses: ./.github/actions/build-setup
      - name: Lint check
        run: npm run lint-check
      - name: Check types
        run: npm run check-types
      - name: create .env.production file
        run: |
          touch .env.production
          echo GATSBY_GA_MEASUREMENT_ID=${{ secrets.TEST_GA_MEASUREMENT_ID }} >> .env.production
          cat .env.production
      - name: Build site
        run: npm run build
