name: Build PR

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/build-pr.yml'
      - 'src/**/*'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Build Setup
        uses: ./.github/actions/build-setup
      - name: Lint check
        run: npm run lint-check
      - name: Check types
        run: npm run check-types
      - name: Build site
        run: npm run build
