name: Build PR

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/build-pr.yml'
      - 'src/**/*'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Lint check
        run: npm run lint-check
      - name: Check types
        run: npm run check-types
      - name: Build site
        run: npm run build