name: Check Pull Request Metadata
on:
  pull_request_target:
    # trigger when the PR title changes
    types: [opened, synchronize, reopened, edited]

jobs:
  check-pr-metadata:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      pull-requests: write # post comments when the PR title doesn't match the "Conventional Commits" rules
    steps:
      - name: Check Pull Request title
        if: contains(fromJSON('["opened", "edited", "reopened"]'), github.event.action)
        uses: bonitasoft/actions/packages/pr-title-conventional-commits@v3

      - name: Add labels to PR
        if: contains(fromJSON('["opened", "synchronize", "reopened"]'), github.event.action)
        uses: actions/labeler@v5
